# ~/.tmuxinator/project_name.yml
# you can make as many windows as you wish...

project_name: [project]
project_root: ~/Sites/[project].dev/public
windows:
  - editor: vim
  - shell:
      layout: even-veritcal
      panes:
        - #empty, will just run plain bash
        - drush sqlc
